# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('abstract', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('abstract', models.CharField(max_length=512)),
                ('min_occurs', models.SmallIntegerField()),
                ('max_occurs', models.SmallIntegerField()),
                ('type', models.CharField(choices=[(0, 'ComplexData'), (1, 'LiteralData'), (2, 'BoundingBoxData')], max_length=1)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('abstract', models.CharField(max_length=512)),
                ('min_occurs', models.SmallIntegerField()),
                ('max_occurs', models.SmallIntegerField()),
                ('type', models.CharField(choices=[(0, 'ComplexOutput'), (1, 'LiteralOutput'), (2, 'BoundingBoxOutput')], max_length=1)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Process')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capabilities_url', models.CharField(max_length=512)),
                ('describe_url', models.CharField(max_length=512)),
                ('execute_url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=128)),
                ('abstract', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('site', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.ServiceProvider'),
        ),
        migrations.AddField(
            model_name='process',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Service'),
        ),
    ]
