# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_identifier', models.CharField(max_length=200)),
                ('input_title', models.CharField(max_length=200)),
                ('input_abstract', models.TextField(default='Add your super descriptive text here...', verbose_name='Descriptive text')),
                ('input_max_occurs', models.DecimalField(decimal_places=10, max_digits=10)),
                ('input_value', models.CharField(max_length=200)),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testWPS.DataTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Outputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_identifier', models.CharField(max_length=200)),
                ('output_title', models.CharField(max_length=200)),
                ('output_abstract', models.TextField(default='Add your super descriptive text here...', verbose_name='Descriptive text')),
                ('output_max_occurs', models.DecimalField(decimal_places=10, max_digits=10)),
                ('output_value', models.CharField(max_length=200)),
                ('output_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testWPS.DataTypes')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_identifier', models.CharField(max_length=200)),
                ('process_title', models.CharField(max_length=200)),
                ('process_abstract', models.TextField(default='Add your super descriptive text here...', verbose_name='Descriptive text')),
                ('process_workflow', models.DecimalField(decimal_places=20, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_title', models.CharField(max_length=200)),
                ('workflow_status', models.CharField(max_length=200)),
                ('workflow_num_processes', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='process_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testWPS.ProcessStatus'),
        ),
        migrations.AddField(
            model_name='outputs',
            name='process_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testWPS.Process'),
        ),
        migrations.AddField(
            model_name='inputs',
            name='process_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testWPS.Process'),
        ),
    ]
